markdown: kramdown
highligter: null
permalink: /:title

url: http://mlaneuville.github.io
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
